### ISSUE TITLE
Plugin doesn't load metadata anymore

### ISSUE THREAD

**Issue by nachfuellbar** [NotSimone/Kobo-Metadata#6]
Seems like Kobo reworked their Website a bit
On the book page there is "book id:" instead of "isbn:" now
Didn't see yet if there are any other changes but since yesterday my metadata comes from other sources only
The cover search is still working though

**Comment by nachfuellbar** [comment]
Seems to work again for me
Dunno why it didn't work yesterday and some hours ago

**Comment by NotSimone** [comment]
I did notice this but they have changed a few times now. Last time they changed the site significantly they spent a few weeks fiddling around with it but it only sometimes loaded the new version (I’m guessing they point some load balancers at their beta page?). I’m planning on waiting for them to settle down before doing a code change but in the meantime if it doesn’t work, I suggest trying a different region or just trying again the next day.

Ditto on the isbn to id thing but it looks like all versions of the site have changed it so I might change that first.
